FROM gableroux/flutter

LABEL version="1.0.0"
LABEL name="flutter"
LABEL repository="https://github.com/jddeep/Flutter-Runner"
LABEL homepage="https://github.com/jddeep/Flutter-Runner"
LABEL com.github.actions.icon="terminal"
LABEL com.github.actions.color="blue"
#release
COPY LICENSE README.md /

ENTRYPOINT ["flutter"]
CMD ["help"]
